jass version 1.5: -  allow '-k' and '-u' to be combined; allow multiple '-k' to be specified -  identify users for whom data is encrypted -  allow encryption for groups (-g)

diff --git a/src/jass b/src/jass
--- a/src/jass
+++ b/src/jass
@@ -2,7 +2,7 @@
 #
 # Copyright (c) 2013 Twitter, Inc.
 #
-# Originally written by Jan Schaumann <jschauma@netmeister.org> in April 2013.
+# Originally written by Jan Schaumann <jschauma@twitter.com> in April 2013.
 #
 # This script allows you to easily share secrets with other users in your
 # organization by way of ssh pubkeys.
@@ -10,6 +10,8 @@
 # Set these two variables to match your use of LDAP for ssh keys.
 #LDAPFIELD="SSHPubkey"
 #LDAPSEARCH="ldapsearch -LLLxh ldap.yourdomain.com -b dc=example,dc=com"
+LDAPFIELD="twSSHPubkey"
+LDAPSEARCH="ldapsearch -LLLxh ldap.local.twitter.com -b dc=ods,dc=twitter,dc=corp"
 
 ### You should not have to edit anything below this line.
 
@@ -24,8 +26,9 @@ umask 077
 PROGNAME="${0##*/}"
 ACTION="encrypt"
 FILE="/dev/stdin"
-KEYFILE=""
+KEYFILES=""
 RECIPIENTS=""
+RECIPIENT_GROUPS=""
 UNAME="$(uname -s)"
 BASE64="base64"
 
@@ -41,21 +44,49 @@ VERBOSITY=0
 ### Functions
 ###
 
+# Read one ssh key per line from the given file and append it to the
+# 'keyfile'.  Add the given recipient name as a comment to the file.
+appendKey() {
+	local readonly keyfile="${TDIR}/keyfile"
+
+	local readonly file="${1}"
+	local recipient="${2}"
+
+	oIFS="${IFS}"
+	IFS='
+'
+
+	# If 'file' and 'recipient' are identical, then we were given a
+	# pathname instead of the keys of a user.  We then provide the
+	# basename of the path as an identifying comment.
+	if [ x"${file}" = x"${recipient}" ]; then
+		recipient="${recipient##*/}"
+	fi
+
+	verbose "Appending keys for '${recipient}' to keyfile'..." 3
+
+	for line in $(cat ${file}); do
+		echo "${line} ${recipient}" >> "${keyfile}"
+	done
+
+	IFS="${oIFS}"
+}
+
 cleanup() {
 	rm -fr "${TDIR}"
 }
 
 convertKeyFiles() {
-	local pubkey
-	local pemfile
+	local pemfile pubkey
 	local success=0
 
 	verbose "Converting ssh pubkeys into PKCS8 format..." 2
 
 	for pubkey in "${KEYDIR}"/*; do
 		# Keys may contain options in the beginning, so nuke the first
-		# option.
-		<"${pubkey}" awk '{ if (NF > 3) { $1=""; }; print }' >"${pubkey}.tmp" && \
+		# option.  Note: since we add the recipient as the last
+		# field, we need to check for NF > 4, not NF > 3!
+		<"${pubkey}" awk '{ if (NF > 4) { $1=""; }; print }' >"${pubkey}.tmp" && \
 			mv "${pubkey}.tmp" "${pubkey}"
 
 		pemfile=$(basename ${pubkey})
@@ -75,7 +106,7 @@ convertKeyFiles() {
 # split the single file containing all pubkeys into per-pubkey files
 createKeyFiles() {
 	local readonly keyfile="${TDIR}/keyfile"
-	local found fp type
+	local found fp recipient type
 
 	found=0
 
@@ -86,6 +117,8 @@ createKeyFiles() {
 	)
 
 	for k in "${KEYDIR}"/.key-*; do
+		# We added the recipient as the last field in getPubkeys.
+		recipient="$(awk '{print $NF}' "${k}")"
 		type=$(ssh-keygen -e -f ${k} | sed -n -e 's/Comment:.*bit \(.*\),.*/\1/p')
 		if [ x"${type}" != x"RSA" ]; then
 			verbose "Key type of type '${type}' not supported. Skipping." 4
@@ -103,7 +136,7 @@ createKeyFiles() {
 		fi
 
 		found=1
-		mv ${k} "${KEYDIR}"/${fp}
+		mv ${k} "${KEYDIR}"/${recipient}-${fp}
 	done
 
 	if [ ${found} -eq 0 ]; then
@@ -114,19 +147,26 @@ createKeyFiles() {
 
 decrypt() {
 	local output="/dev/stdout"
-	local outfile
-	local skey
+	local outfile skey skeyfp
 	local f
 	local found=0
 
 	local readonly msgdir="${TDIR}/message"
-	local readonly localfp=$(ssh-keygen -l -f "${KEYFILE}" | awk '{print $2}')
+	local readonly localfp=$(ssh-keygen -l -f ${KEYFILES} | awk '{print $2}')
 
 	verbose "Decrypting..."
 
 	verbose "Decoding data..." 2
 	verbose "Splitting input..." 3
-	cat "${FILE}" | ( cd "${TDIR}" && awk '/^begin-base64 / { f="data"i++; } { print > f;}' )
+	cat "${FILE}" | ( cd "${TDIR}" && awk '/^begin-base64 / { 		\
+							f="data"i++; }		\
+						{ print > f; }			\
+						/^====/ { close(f); }' )
+
+	if [ $? -gt 0 ]; then
+		echo "Invalid input?" >&2
+		exit 1
+	fi
 
 	verbose "Uudecoding ecnrypted message..." 3
 	( mkdir -p "${msgdir}" && cd "${msgdir}" && uudecode ../data0 )
@@ -144,8 +184,9 @@ decrypt() {
 
 	for f in "${KEYDIR}"/*; do
 		skey=$(basename "${f}")
+		skeyfp=$(echo ${skey} | sed -e 's/.*-//')
 
-		if [ x"${skey}" = x"${localfp}" ]; then
+		if [ x"${skeyfp}" = x"${localfp}" ]; then
 			verbose "Using ${skey}..." 4
 			found=1
 			break
@@ -153,12 +194,12 @@ decrypt() {
 	done
 
 	if [ ${found} -eq 0 ]; then
-		echo "Data was not encrypted for the key in ${KEYFILE}." >&2
+		echo "Data was not encrypted for the key in ${KEYFILES}." >&2
 		exit 1
 	fi
 
 	verbose "Decrypting session key..." 2
-	openssl rsautl -inkey "${KEYFILE}" -decrypt -in "${KEYDIR}/${skey}" -out "${TDIR}/skey"
+	openssl rsautl -inkey ${KEYFILES} -decrypt -in "${KEYDIR}/${skey}" -out "${TDIR}/skey"
 
 	verbose "Decrypting message using session key..." 2
 	openssl enc -d -aes-256-cbc -pass "file:${TDIR}/skey"	\
@@ -198,21 +239,64 @@ encrypt() {
 	done
 }
 
+expandGroup() {
+	local readonly group="${1}"
+	local all group_users
+
+	verbose "Expanding group '${group}'..." 2
+
+	# Supplementary groups are easy...
+	verbose "Expanding group '${group}' by supplementary group membership..." 3
+	group_users="$(grep "^${group}:" /etc/group | awk -F: '{print $NF}' | tr ',' ' ')"
+	all="${group_users}"
+	if [ -n "${all}" ]; then
+		verbose "${all}" 4
+	fi
+
+	# ...but some users have primary groups...
+	gid=$(grep "^${group}:" /etc/group | awk -F: '{print $3}')
+	if [ -n "${gid}" ]; then
+		verbose "Expanding group '${group}' by primary group membership..." 3
+		group_users="$(awk -v gid="${gid}" -F: '{ if ($4 == gid) { print $1; }}' /etc/passwd)"
+		if [ -n "${group_users}" ]; then
+			all="${group_users} ${all}"
+			verbose "${all}" 4
+		fi
+	fi
+
+	# ...and of course there's LDAP.
+	if [ -z "${all}" ]; then
+		if ldapVarCheck; then
+			verbose "Expanding group '${group}' from LDAP..." 3
+			group_users="$(${LDAPSEARCH} cn="${group}" memberUid | grep -v ^dn: | awk '{print $2}')"
+			if [ -n "${group_users}" ]; then
+				all="${group_users} ${all}"
+				verbose "${all}" 4
+			fi
+		fi
+	fi
+
+	RECIPIENTS="${RECIPIENTS} $(echo ${all} | sort -u)"
+}
+
 generateSessionKey() {
 	verbose "Generating a session key..." 2
 
 	openssl rand 32 -base64 -out "${SESSION_KEY}" 2>/dev/null
 }
 
-# After this completes, all available pubkeys will be stored under the
-# ${KEYDIR}, one key per file, each named by the fingerprint of the
-# pubkey.
+# Retrieve all available keys for all recipients and store them in a
+# single file, 'keyfile'.
 getPubkeys() {
 	verbose "Identifying/retrieving ssh pubkeys..." 2
 
 	local found=0
-	local etcfile tildefile
+	local etcfile group kfile tildefile
 	local readonly keyfile="${TDIR}/keyfile"
+
+	for group in ${RECIPIENT_GROUPS}; do
+		expandGroup "${group}"
+	done
 
 	if [ -n "${RECIPIENTS}" ]; then
 		for r in ${RECIPIENTS}; do
@@ -223,7 +307,7 @@ getPubkeys() {
 			for f in "${tildefile}" "${etcfile}"; do
 				verbose "Trying '${f}'..." 3
 				if [ -r "${f}" ]; then
-					cat "${f}" >> "${keyfile}"
+					appendKey "${f}" "${r}"
 					found=1
 				fi
 			done
@@ -231,14 +315,16 @@ getPubkeys() {
 			if [ ${found} -eq 0 ]; then
 				getPubkeysFromLDAP "${r}"
 				if [ -s "${LDAP_KEYFILE}" ]; then
-					cat "${LDAP_KEYFILE}" >> "${keyfile}"
+					appendKey "${LDAP_KEYFILE}" "${r}"
 				fi
 			fi
 		done
 	fi
 
-	if [ -n "${KEYFILE}" ]; then
-		cp "${KEYFILE}" "${keyfile}"
+	if [ -n "${KEYFILES}" ]; then
+		for kfile in ${KEYFILES}; do
+			appendKey "${kfile}" "${kfile}"
+		done
 	fi
 
 	if [ ! -s "${keyfile}" ]; then
@@ -250,12 +336,7 @@ getPubkeys() {
 getPubkeysFromLDAP() {
 	local readonly user="${1}"
 
-	if [ -z "${LDAPSEARCH}" -o -z "${LDAPFIELD}" ]; then
-		echo "Use of LDAP not configured." >&2
-		echo "Please set the LDAPSEARCH and LDAPFIELD variables near the top of" >&2
-		echo "this script or in your environment." >&2
-		return
-	fi
+	ldapVarCheck || return
 
 	verbose "Retrieving ssh pubkeys for '${user}' from LDAP..." 3
 
@@ -304,36 +385,66 @@ Usage: ${PROGNAME} [-dehv] [-f file] [-k key] [-u user]
 EOH
 }
 
+ldapVarCheck() {
+	if [ -z "${LDAPSEARCH}" -o -z "${LDAPFIELD}" ]; then
+		echo "Use of LDAP not configured." >&2
+		echo "Please set the LDAPSEARCH and LDAPFIELD variables near the top of" >&2
+		echo "this script or in your environment." >&2
+		return 1
+	fi
+	return 0
+}
+
 
 # purpose : check that all important variables are set correctly
 # input   : none
 # output  : none, globals may have been modified, may abort on error
 
 varCheck() {
-	local file
+	local file kfiles n
 
 	verbose "Checking that all variables look ok..."
-	if [ -n "${KEYFILE}" -a ! -r "${KEYFILE}" ]; then
-		echo "Unable to read the key file '${KEYFILE}'." >&2
-		exit 1
+	n=0
+	if [ -n "${KEYFILES}" ]; then
+		for file in ${KEYFILES}; do
+			if [ ! -r "${file}" ]; then
+				echo "Skipping unreadable key file '${file}'." >&2
+			else
+				kfiles="${file} ${kfiles}"
+				n=$(( ${n} + 1 ))
+			fi
+		done
+		if [ -z "${kfiles}" ]; then
+			echo "No usable key file found." >&2
+			exit 1
+		fi
+		KEYFILES="${kfiles}"
 	fi
 
 	if [ x"${ACTION}" = x"encrypt" ]; then
-		if [ -z "${KEYFILE}" -a -z "${RECIPIENTS}" ] ||
-			[ -n "${KEYFILE}" -a -n "${RECIPIENTS}" ]; then
-			echo "You need to provide either a key file or a username." >&2
+		if [ -z "${KEYFILES}" -a -z "${RECIPIENTS}" -a -z "${RECIPIENT_GROUPS}" ]; then
+			echo "You need to provide either a key file, a group, or a username." >&2
 			exit 1
 		fi
 	else
+		if [ -n "${RECIPIENT_GROUPS}" ]; then
+			echo "You can't specify a group when decrypting." >&2
+			exit 1
+		fi
 		if [ -n "${RECIPIENTS}" ]; then
 			echo "You can't specify a user when decrypting." >&2
 			exit 1
 		fi
 
-		if [ -z "${KEYFILE}" ]; then
+		if [ ${n} -gt 1 ]; then
+			echo "Please only specify a single key file when decrypting." >&2
+			exit 1
+		fi
+
+		if [ -z "${KEYFILES}" ]; then
 			verbose "No key specified, trying ~/.ssh/id_rsa..." 2
-			KEYFILE="${HOME}/.ssh/id_rsa"
-			if [ ! -r "${KEYFILE}" ]; then
+			KEYFILES="${HOME}/.ssh/id_rsa"
+			if [ ! -r "${KEYFILES}" ]; then
 				echo "No key found.  Please use '-k'." >&2
 				exit 1
 			fi
@@ -369,7 +480,7 @@ verbose() {
 
 trap 'cleanup' 0
 
-while getopts 'def:hk:u:v' opt; do
+while getopts 'def:g:hk:u:v' opt; do
 	case ${opt} in
 		d)
 			ACTION="decrypt"
@@ -382,13 +493,16 @@ while getopts 'def:hk:u:v' opt; do
 				FILE="${OPTARG}"
 			fi
 		;;
+		g)
+			RECIPIENT_GROUPS="${OPTARG} ${RECIPIENT_GROUPS}"
+		;;
 		h\?)
 			usage
 			exit 0
 			# NOTREACHED
 		;;
 		k)
-			KEYFILE="${OPTARG}"
+			KEYFILES="${OPTARG} ${KEYFILES}"
 		;;
 		u)
 			RECIPIENTS="${OPTARG} ${RECIPIENTS}"
